### ISSUE TITLE
Logout and ipv6 validation problems in web interface

### ISSUE THREAD

**Issue by sraustein** [dragonresearch/rpki.net#429]
Hello, 

I use rpki.net tools version retrieved sunday in subversion repository. I work with Debian unstable, Apache2 2.2.22, libapache2-mod-wsgi 3.3 and Django 1.4.3.

I have two problems with the web interface of CA tools.

First : logout doesn't work. I click on "Log Out" in the web interface and i get an exception : login() got an unexpected keyword argument 'next_page'. I am never disconnected. See traceback in attachments.

Two : I have two users in my scenario : "RIR" and "LIR". RIR has these resources (in root cert) :
- AS64496 ; 
- 192.0.2.0/24
- 2001:db8::/32. 

I have no problem to create an ROA for 192.0.2.0/24. RIR can also delegate this resource to LIR and LIR can create ROA. No problem.

But i can't create an ROA for 2001:db8::/32 because i always get an error "prefix is not allocated to you". 

However :
- I see 2001:db8::/32 in "Resources" and "Unallocated Resources" parts of web gui.
- RIR can delegate this resource to LIR without error but LIR can't create ROA because he gets the same error message.

I thought that error is uppercase/lowercase problem but try with "2001:0DB8::/32" doesn't work better. 

I also try with numeric-only prefix, 2001:660::/32, but doesn't work. Obviously, i added 2001:660::/32 in root cert and this resource was listed in "Resources" and "Unallocated Resources" parts of web gui before my test.

Regards.

_Trac ticket #414 component gui priority minor, owner melkins, created by glucas on 2013-02-19T23:57:49Z, last modified 2013-02-20T21:15:15Z_
